### ISSUE TITLE
Add a visual monitor.

### ISSUE THREAD

**Issue by mldk-tech** [Gizra-Shoov/huji-registration-shoov#1]
http://dev-huji-reg.pantheon.io/

**Comment by mldk-tech** [comment]
@amitaibu - The test not start 
Can you please check it? https://app.shoov.io/#/repos/20309

**Comment by amitaibu** [comment]
The above link is connected to https://github.com/Gizra/huji-registration

You might have enabled the wrong repo

**Comment by mldk-tech** [comment]
Right, I do not see GIZRA-SHOOV in the organization list.
I did set out and entering into the system but still I do not see GIZRA-SHOOV

**Comment by mldk-tech** [comment]
![selection_002](https://cloud.githubusercontent.com/assets/5812423/11360600/beaeaabc-928e-11e5-9555-3271068a9e76.png)

**Comment by amitaibu** [comment]
Seems this is still not runnin on shoov.

**Comment by mldk-tech** [comment]
I open a issue : https://github.com/shoov/shoov/issues/319

![selection_017](https://cloud.githubusercontent.com/assets/5812423/11613759/4e30f334-9c35-11e5-9e20-b06c5525285b.png)
But I have the yml file in the project
